spring:
  application.name: localpath

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  docker:
    compose:
      lifecycle-management: start_only


  jwt:
    accessToken-expire-length: 600000
    refresh-expire-length: 2592000000
    secret: ${JWT_SECRET_KEY}
